BEGIN;
DO $$
DECLARE
  v_prop uuid; v_user uuid; v_rec uuid; v_res uuid; v_lob uuid; v_rep uuid;
  v_cash_net numeric; v_pos_net numeric;
BEGIN
  SELECT id INTO v_prop FROM properties WHERE name ILIKE '%ривърсайд%' LIMIT 1;
  SELECT id INTO v_user FROM user_profiles LIMIT 1;
  INSERT INTO departments (property_id, name, manager_id) VALUES
    (v_prop, 'Рецепция', v_user), (v_prop, 'Ресторант', v_user)
    ON CONFLICT (property_id, name) DO NOTHING;
  SELECT id INTO v_rec FROM departments WHERE property_id=v_prop AND name='Рецепция';
  SELECT id INTO v_res FROM departments WHERE property_id=v_prop AND name='Ресторант';
  SELECT id INTO v_lob FROM departments WHERE property_id=v_prop AND name='Лоби Бар';
  RAISE NOTICE 'rec=% res=% lob=%', v_rec, v_res, v_lob;

  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-01', v_user, 'APPROVED', 3852.93, 2709.94) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 3738.07, 0.0, 2494.12, 0.0, 2494.12);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 114.86, 215.82, 215.82);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-02', v_user, 'APPROVED', 1837.11, 603.06) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 1348.34, 0.0, 485.96, 0.0, 485.96);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 29.66, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 459.11, 117.1, 117.1);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-03', v_user, 'APPROVED', 404.73, 646.02) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 273.06, 0.0, 557.84, 0.0, 557.84);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 131.67, 88.18, 88.18);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-04', v_user, 'APPROVED', 1034.5, 692.82) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 965.26, 0.0, 602.92, 0.0, 602.92);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 69.24, 89.9, 89.9);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-05', v_user, 'APPROVED', 316.75, 360.91) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 249.0, 0.0, 242.86, 0.0, 242.86);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 67.75, 118.05, 118.05);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-06', v_user, 'APPROVED', 142.96, 158.06) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 55.24, 0.0, 51.67, 0.0, 51.67);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 87.72, 106.39, 106.39);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-07', v_user, 'APPROVED', 205.05, 104.65) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 161.29, 0.0, 62.18, 0.0, 62.18);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 43.76, 42.47, 42.47);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-08', v_user, 'APPROVED', 60.59, 273.04) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 13.29, 0.0, 212.64, 0.0, 212.64);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 47.3, 60.4, 60.4);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-09', v_user, 'APPROVED', 508.03, 38.34) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 441.8, 0.0, 4.59, 0.0, 4.59);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 66.23, 33.75, 33.75);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-10', v_user, 'APPROVED', 493.05, 126.85) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 383.68, 0.0, 5.12, 0.0, 5.12);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 109.37, 121.73, 121.73);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-11', v_user, 'APPROVED', 698.83, 112.97) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 450.88, 0.0, 10.74, 0.0, 10.74);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 247.95, 102.23, 102.23);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-12', v_user, 'APPROVED', 183.25, 96.6) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 23.04, 0.0, 23.02, 0.0, 23.02);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 160.21, 73.58, 73.58);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-13', v_user, 'APPROVED', 442.87, 1701.29) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 287.0, 0.0, 1591.0, 0.0, 1591.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 155.87, 110.29, 110.29);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-14', v_user, 'APPROVED', 231.35, 189.15) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 29.68, 0.0, 141.02, 0.0, 141.02);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 201.67, 48.13, 48.13);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-15', v_user, 'APPROVED', 363.03, 352.1) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 126.59, 0.0, 275.67, 0.0, 275.67);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 236.44, 76.43, 76.43);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-16', v_user, 'APPROVED', 357.89, 543.3) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 74.19, 0.0, 453.26, 0.0, 453.26);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 283.7, 90.04, 90.04);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-17', v_user, 'APPROVED', 2082.17, 1137.35) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 1885.38, 0.0, 825.06, 0.0, 825.06);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 196.79, 312.29, 312.29);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-18', v_user, 'APPROVED', 223.84, 293.54) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 58.88, 0.0, 183.81, 0.0, 183.81);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 164.96, 109.73, 109.73);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-19', v_user, 'APPROVED', 161.47, 185.63) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 124.9, 0.0, 166.95, 0.0, 166.95);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 36.57, 18.68, 18.68);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-20', v_user, 'APPROVED', 17.92, 4540.83) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 2.56, 0.0, 4527.8, 0.0, 4527.8);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 15.36, 13.03, 13.03);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-21', v_user, 'APPROVED', 330.0, 175.97) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 289.32, 0.0, 149.11, 0.0, 149.11);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 40.68, 26.86, 26.86);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-22', v_user, 'APPROVED', 114.62, 39.84) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 86.05, 0.0, 28.6, 0.0, 28.6);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 28.57, 11.24, 11.24);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-23', v_user, 'APPROVED', 297.08, 286.59) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 242.89, 0.0, 271.26, 0.0, 271.26);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 54.19, 15.33, 15.33);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-24', v_user, 'APPROVED', 1878.08, 179.59) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 1826.86, 0.0, 128.37, 0.0, 128.37);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 51.22, 51.22, 51.22);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-25', v_user, 'APPROVED', 118.05, 1569.03) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 68.75, 0.0, 1540.41, 0.0, 1540.41);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 49.3, 28.62, 28.62);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-26', v_user, 'APPROVED', 372.56, 391.42) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 306.92, 0.0, 347.08, 0.0, 347.08);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 65.64, 44.34, 44.34);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-27', v_user, 'APPROVED', 301.91, 75.65) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 256.15, 0.0, 50.02, 0.0, 50.02);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 45.76, 25.63, 25.63);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-28', v_user, 'APPROVED', 116.74, 71.02) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 56.91, 0.0, 60.29, 0.0, 60.29);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 59.83, 10.73, 10.73);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-29', v_user, 'APPROVED', 99.03, 23.52) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 70.42, 0.0, 20.46, 0.0, 20.46);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 28.61, 3.06, 3.06);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-30', v_user, 'APPROVED', 1204.44, 2031.28) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 1048.48, 0.0, 1984.47, 0.0, 1984.47);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 155.96, 46.81, 46.81);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-01-31', v_user, 'APPROVED', 695.72, 1523.36) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 559.26, 0.0, 1484.43, 0.0, 1484.43);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 136.46, 38.93, 38.93);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-01', v_user, 'APPROVED', 1024.38, 646.93) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 841.11, 0.0, 632.09, 0.0, 632.09);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 183.27, 14.84, 14.84);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-02', v_user, 'APPROVED', 187.57, 192.72) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 144.88, 0.0, 183.0, 0.0, 183.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 42.69, 9.72, 9.72);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-03', v_user, 'APPROVED', 264.21, 143.44) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 254.0, 0.0, 143.44, 0.0, 143.44);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 10.21, 0.0, 0.0);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-04', v_user, 'APPROVED', 624.69, 650.9) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 573.82, 0.0, 562.93, 0.0, 562.93);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 50.87, 87.97, 87.97);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-05', v_user, 'APPROVED', 333.86, 956.86) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 326.71, 0.0, 923.91, 0.0, 923.91);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 7.15, 32.95, 32.95);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-06', v_user, 'APPROVED', 886.02, 1161.43) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 704.99, 0.0, 1077.83, 0.0, 1077.83);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 181.03, 83.6, 83.6);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-07', v_user, 'APPROVED', 539.22, 1047.62) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 317.21, 0.0, 987.26, 0.0, 987.26);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 222.01, 60.36, 60.36);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-08', v_user, 'APPROVED', 464.39, 600.42) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 417.88, 0.0, 505.19, 0.0, 505.19);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 46.51, 95.23, 95.23);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-09', v_user, 'APPROVED', 276.35, 171.35) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 192.51, 0.0, 122.49, 0.0, 122.49);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 83.84, 48.86, 48.86);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-10', v_user, 'APPROVED', 662.35, 783.84) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 597.19, 0.0, 656.7, 0.0, 656.7);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 65.16, 127.14, 127.14);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-11', v_user, 'APPROVED', 418.48, 752.59) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 302.49, 0.0, 671.76, 0.0, 671.76);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 115.99, 80.83, 80.83);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-12', v_user, 'APPROVED', 226.72, 170.83) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 132.62, 0.0, 81.31, 0.0, 81.31);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 94.1, 89.52, 89.52);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-13', v_user, 'APPROVED', 1720.78, 272.94) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 1527.31, 0.0, 175.87, 0.0, 175.87);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 15.34, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 178.13, 97.07, 97.07);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-14', v_user, 'APPROVED', 1308.37, 149.35) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 1061.35, 0.0, 99.25, 0.0, 99.25);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 247.02, 50.1, 50.1);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-15', v_user, 'APPROVED', 407.05, 1431.89) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 164.94, 0.0, 1320.46, 0.0, 1320.46);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 242.11, 111.43, 111.43);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-16', v_user, 'APPROVED', 251.96, 62.54) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 48.64, 0.0, 7.56, 0.0, 7.56);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 203.32, 54.98, 54.98);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-17', v_user, 'APPROVED', 864.7, 301.2) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 653.0, 0.0, 245.22, 0.0, 245.22);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 211.7, 55.98, 55.98);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-18', v_user, 'APPROVED', 261.87, 136.81) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 83.11, 0.0, 65.9, 0.0, 65.9);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 178.76, 70.91, 70.91);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-19', v_user, 'APPROVED', 899.48, 197.89) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 694.23, 0.0, 117.76, 0.0, 117.76);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 205.25, 80.13, 80.13);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-20', v_user, 'APPROVED', 289.65, 302.91) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 92.91, 0.0, 229.7, 0.0, 229.7);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 30.68, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 166.06, 73.21, 73.21);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-21', v_user, 'APPROVED', 771.02, 1206.43) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 639.51, 0.0, 938.37, 0.0, 938.37);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 131.51, 268.06, 268.06);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-22', v_user, 'APPROVED', 203.61, 345.43) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 155.43, 0.0, 81.87, 0.0, 87.87);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 1.53, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 46.65, 263.56, 263.56);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-23', v_user, 'APPROVED', 285.12, 264.03) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 259.59, 0.0, 61.4, 0.0, 61.4);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 25.53, 202.63, 202.63);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-24', v_user, 'APPROVED', 155.33, 143.01) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 127.52, 0.0, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 21.48, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 6.33, 143.01, 143.01);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-25', v_user, 'APPROVED', 520.29, 136.49) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 478.48, 0.0, 120.4, 0.0, 120.4);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 6.66, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 35.15, 16.09, 16.09);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-26', v_user, 'APPROVED', 374.32, 103.27) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 332.35, 0.0, 95.21, 0.0, 95.21);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 41.97, 8.06, 8.06);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-27', v_user, 'APPROVED', 593.32, 395.48) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 538.82, 0.0, 391.38, 0.0, 391.38);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 54.5, 4.1, 4.1);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-02-28', v_user, 'APPROVED', 2488.73, 3805.89) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 2282.51, 0.0, 3734.29, 0.0, 3734.29);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 108.99, 25.33, 25.33);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 97.23, 46.27, 46.27);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-01', v_user, 'APPROVED', 340.74, 86.54) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 153.21, 0.0, 59.42, 0.0, 59.42);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 113.35, 7.67, 7.67);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 74.18, 19.45, 19.45);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-02', v_user, 'APPROVED', 723.21, 175.68) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 562.91, 0.0, 133.22, 0.0, 133.22);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 98.2, 19.96, 19.96);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 62.1, 22.5, 22.5);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-03', v_user, 'APPROVED', 73.57, 71.61) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 41.71, 0.0, 39.39, 0.0, 39.39);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 31.86, 32.22, 32.22);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-04', v_user, 'APPROVED', 49.34, 108.17) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 17.91, 0.0, 92.58, 0.0, 92.58);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 19.42, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 12.01, 15.59, 15.59);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-05', v_user, 'APPROVED', 73.14, 9.97) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 68.02, 0.0, 1.79, 0.0, 1.79);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 5.12, 8.18, 8.18);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-06', v_user, 'APPROVED', 1771.42, 18.93) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 1684.56, 0.0, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 32.26, 4.1, 4.1);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 54.6, 14.83, 14.83);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-07', v_user, 'APPROVED', 392.84, 95.59) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 30.7, 0.0, 71.6, 0.0, 71.6);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 172.31, 4.1, 4.1);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 189.83, 19.89, 19.89);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-08', v_user, 'APPROVED', 326.92, 207.15) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 177.09, 0.0, 181.84, 0.0, 181.84);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 35.28, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 114.55, 25.31, 25.31);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-09', v_user, 'APPROVED', 53.68, 30.44) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 20.46, 0.0, 20.46, 0.0, 20.46);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 33.22, 9.98, 9.98);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-10', v_user, 'APPROVED', 111.83, 161.66) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 98.0, 0.0, 140.7, 0.0, 140.7);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 13.83, 20.96, 20.96);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-11', v_user, 'APPROVED', 2.56, 31.73) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 0.0, 0.0, 20.46, 0.0, 20.46);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 2.56, 11.27, 11.27);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-12', v_user, 'APPROVED', 4.86, 128.64) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 0.0, 0.0, 123.01, 0.0, 123.01);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 4.86, 5.63, 5.63);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-13', v_user, 'APPROVED', 273.74, 514.97) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 208.26, 0.0, 458.39, 0.0, 458.39);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 14.07, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 51.41, 56.58, 56.58);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-14', v_user, 'APPROVED', 1017.24, 1379.53) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 926.69, 0.0, 1283.17, 0.0, 1283.17);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 14.08, 16.85, 16.85);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 76.47, 79.51, 79.51);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-15', v_user, 'APPROVED', 340.35, 130.29) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 290.79, 0.0, 88.16, 0.0, 88.16);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 49.56, 42.13, 42.13);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-16', v_user, 'APPROVED', 136.84, 31.67) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 119.45, 0.0, 7.67, 0.0, 7.67);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 9.73, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 7.66, 24.0, 24.0);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-17', v_user, 'APPROVED', 65.83, 50.0) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 64.3, 0.0, 50.0, 0.0, 50.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 1.53, 0.0, 0.0);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-18', v_user, 'APPROVED', 80.34, 1.53) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 80.34, 0.0, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 0.0, 1.53, 1.53);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-19', v_user, 'APPROVED', 66.3, 30.95) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 50.0, 0.0, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 16.3, 30.95, 30.95);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-20', v_user, 'APPROVED', 485.41, 650.59) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 428.37, 0.0, 571.04, 0.0, 571.04);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 11.26, 7.94, 7.94);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 45.78, 71.61, 71.61);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-21', v_user, 'APPROVED', 381.9, 190.0) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 242.85, 0.0, 143.69, 0.0, 143.69);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 5.63, 2.05, 2.05);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 133.42, 44.26, 44.26);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-22', v_user, 'APPROVED', 459.24, 10.23) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 425.26, 0.0, 10.23, 0.0, 10.23);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 8.7, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 25.28, 0.0, 0.0);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-23', v_user, 'APPROVED', 52.7, 0.0) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 44.0, 0.0, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 8.7, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 0.0, 0.0, 0.0);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-24', v_user, 'APPROVED', 17.91, 35.8) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 5.12, 0.0, 35.8, 0.0, 35.8);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 7.68, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 5.11, 0.0, 0.0);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-25', v_user, 'APPROVED', 50.0, 0.0) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 50.0, 0.0, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 0.0, 0.0, 0.0);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-26', v_user, 'APPROVED', 222.29, 53.48) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 218.2, 0.0, 50.42, 0.0, 50.42);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 4.09, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 0.0, 3.06, 3.06);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-27', v_user, 'APPROVED', 1434.91, 183.63) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 1410.36, 0.0, 181.07, 0.0, 181.07);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 5.63, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 18.92, 2.56, 2.56);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-28', v_user, 'APPROVED', 356.05, 220.38) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 321.78, 0.0, 205.03, 0.0, 205.03);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 17.4, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 16.87, 15.35, 15.35);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-29', v_user, 'APPROVED', 7.68, 107.79) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 7.68, 0.0, 96.52, 0.0, 96.52);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 0.0, 11.27, 11.27);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-30', v_user, 'APPROVED', 25.31, 0.0) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 2.56, 0.0, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 22.75, 0.0, 0.0);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-03-31', v_user, 'APPROVED', 62.15, 83.75) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 5.12, 0.0, 50.0, 0.0, 50.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 57.03, 33.75, 33.75);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-04-01', v_user, 'APPROVED', 144.51, 0.0) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 110.23, 0.0, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 34.28, 0.0, 0.0);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-04-02', v_user, 'APPROVED', 148.54, 249.12) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 145.98, 0.0, 202.53, 0.0, 202.53);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 0.0, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 2.56, 46.59, 46.59);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-04-03', v_user, 'APPROVED', 381.76, 442.27) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 369.48, 0.0, 425.64, 0.0, 425.64);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 4.1, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 8.18, 16.63, 16.63);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-04-04', v_user, 'APPROVED', 483.89, 547.95) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 377.37, 0.0, 505.49, 0.0, 505.49);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 15.88, 15.88, 15.88);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 90.64, 26.58, 26.58);
  INSERT INTO daily_reports (property_id, date, created_by_id, status, total_cash_net, total_pos_net) VALUES (v_prop, '2026-04-05', v_user, 'APPROVED', 769.15, 733.22) RETURNING id INTO v_rep;
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, cash_refund, pos_income, z_cash, pos_report_amount) VALUES (v_rep, v_rec, 629.65, 0.0, 708.73, 0.0, 708.73);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_res, 7.42, 0.0, 0.0);
  INSERT INTO daily_report_lines (daily_report_id, department_id, cash_income, pos_income, pos_report_amount) VALUES (v_rep, v_lob, 132.08, 24.49, 24.49);
END $$;
COMMIT;
